frontend:
  - client/*
  - client/**/*
backend:
  - server/*
  - server/**/*
github:
  - .github/*
  - .github/**/*
package.json:
  - package.json
  - package-lock.json
  - */package.json
  - */package-lock.json
  - */**/package.json
  - */**/package-lock.json
