name: Approve on Label
on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  approve-on-label:
    name: Approve on Label
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Added label
        if: github.event.action == 'labeled'
        run: echo "Added label"
      - name: Removed label
        if: github.event.action == 'unlabeled'
        run: echo "Removed label"
