name: Auto approve
on: pull_request

jobs:
  auto-approve:
    name: Auto Approve
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      if: github.actor == 'VictorWinberg'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
