name: Build
on: [pull_request]

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install and cache dependencies
        uses: cypress-io/github-action@v1
        with:
          runTests: false

      - name: build
        run: npm run build

      - name: lint
        run: npm run lint

      - name: test
        run: npm test

      - name: codecov
        run: bash <(curl -s https://codecov.io/bash)

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
