name: ESLint

on: [push]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - name: ESLint checks
      uses: gimenete/eslint-action@1.0
    - name: Run ESLint
      uses: stefanoeb/eslint-action@1.0.0
