name: ESLint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ESLint checks
      uses: gimenete/eslint-action@1.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run ESLint
      uses: stefanoeb/eslint-action@1.0.0
