name: Labeler
on: [pull_request]

jobs:
  label:
    name: "Directory Labeler"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  pr-labeler:
    name: "Branch Labeler"
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  auto-label:
    name: "Pattern Labeler"
    runs-on: ubuntu-latest
    steps:
      - uses: banyan/auto-label@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  wip:
    name: "WIP Labeler"
    runs-on: ubuntu-latest
    steps:
      - uses: wip/action@master
